### ISSUE TITLE
Styles(Theme)

### ISSUE THREAD

**Issue by StevenZelenak** [nss-evening-cohort-11/nutshell-jedis#11]
## User Story
As a user, I should see uniform styles through the site.

## AC
WHEN the page loads
THEN I should see a consistent color theme
AND a custom font
AND lots of clean styles throughout the site

## Dev Notes
* Install `Rajdhani` Google Font
* Use custom color scheme included in comments and style cards similarly using Bootstrap and custom colors
* Create custom button styles
* Make all forms consistent in appearance

**Comment by StevenZelenak** [comment]
![](https://files.slack.com/files-pri/T03F2SDTJ-F011RK03M2N/screen_shot_2020-04-13_at_8.30.16_pm.png)

**Comment by StevenZelenak** [comment]
![image](https://user-images.githubusercontent.com/57852913/79176531-1ce52f80-7dc6-11ea-8c8f-18d8cb843419.png)

**Comment by StevenZelenak** [comment]
![image](https://user-images.githubusercontent.com/57852913/79176551-266e9780-7dc6-11ea-8fba-6e8c371b9f1a.png)

**Comment by John-Fleming** [comment]
Site inspo https://jurassicworldevolution.com/en-US#features
