### ISSUE TITLE
Chaos Monkey

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/nutshell-jedis#3]
# User Stories
- [x] As a user, I should be shown a toast whenever the Chaos Monkey strikes
- [x] As a user, I should allow the Chaos Monkey to do one random act for a set interval
- [x] As a user, the Chaos Monkey should have a chance to break down a random ride
- [x] As a user, the Chaos Monkey should have a chance to kidnap a random staff member
- [x] As a user, the Chaos Monkey should have a chance to break a random piece of equipment

# AC
WHEN the page loads
THEN the Chaos Monkey is unleashed
AND he breaks down random rides
AND he kidnaps a random staff member
AND he breaks a random piece of a equipment
AND when he does this, a Bootstrap alert pops down to inform the user of the Chaos Monkey's transgression

# Dev Notes 
+ create a function called ChaosMonkey
+ create a const called ```randCategory``` that multiplies ```Math.ceil(Math.random() * 3)``` by 3-- 1 equals staff, 2 equals rides, 3 equals equipment
+ depending what is called, corresponding function is called (eg. if 1, then call ```get```)
+ write a case switch for the ```randCategory``` that has cases of 1, 2, and 3
+ call ```.then((response) => ```
+ create a const called ```randId``` that multiplies ```Math.ceil(Math.random() * responseArray.length)
+ const getSingleThing = (randCategory, randId) => axios.patch(`${baseUrl}/${randCategory}/${randId}.json`, {isBroken: true});

**Comment by AaronLain** [comment]
Bootstrap alert for Chaos Monkey 
```
<div class="alert alert-danger" role="alert">
  This is a danger alert—check it out!
</div>
```
